indicators:
  - key: "CHW_001"
    description: "Total U5 children"
    indicatorQuery: "select count(distinct baseEntityId) from event where eventType = 'Child Registration' and eventDate = '%s'"

  - key: "CHW_002"
    description: "Children (0-11 months) who died in the last year"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Remove Child Under 5' and eventDate = '%s' and event.baseEntityId in (select ec_child.base_entity_id
      from ec_child where date(ec_child.dob) >= date('now', '-11 month') and date(ec_child.dod) >= date('now', '-12 month'))"
